name: Laravel CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: write
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.4"
          extensions: >
            ctype,
            curl,
            dom,
            fileinfo,
            filter,
            hash,
            mbstring,
            openssl,
            pcre,
            pdo,
            session,
            tokenizer,
            xml
          tools: composer:v2

      - name: Install Dependencies
        run: |
          composer install --no-interaction --no-progress --prefer-dist
          npm ci

      - name: Setup CI Environment
        run: |
          php artisan env:decrypt --env=test --key=${{ secrets.TEST_ENV_KEY }}
          cp .env.ci .env
          rm .env.ci

      - name: Generate Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Run ESLint
        run: npm run lint

      - name: Check code format with Prettier
        run: npm run format:check

      - name: Run Laravel Pint
        run: vendor/bin/pint --test

      - name: Build assets
        run: npm run build

      - name: Run tests with Pest
        run: ./vendor/bin/pest --coverage --min=85 --coverage-clover=reports/coverage.xml

      - name: Archive coverage data
        uses: actions/upload-artifact@v4
        with:
          name: php-coverage-data
          path: reports/coverage.xml

  build:
    needs: test
    runs-on: ubuntu-latest

    env:
      SHORT_SHA: ${{ github.sha }}
      IMAGE_PHP_FPM_BASE: ghcr.io/hana-ri/learn-laravel-12-pipeline/php-fpm
      IMAGE_NGINX_BASE: ghcr.io/hana-ri/learn-laravel-12-pipeline/nginx

    steps:
      - uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "SHORT_SHA_ENV=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PHP-FPM Docker Image
        run: |
          docker build \
            --target fpm_server \
            --build-arg BUILD_ARGUMENT_ENV=prod \
            -t ${{ env.IMAGE_PHP_FPM_BASE }}:${{ env.SHORT_SHA_ENV }} \
            -t ${{ env.IMAGE_PHP_FPM_BASE }}:latest \
            -f .docker/common/Dockerfile .

      - name: Push PHP-FPM Docker Image
        run: |
          docker push ${{ env.IMAGE_PHP_FPM_BASE }}:${{ env.SHORT_SHA_ENV }}
          docker push ${{ env.IMAGE_PHP_FPM_BASE }}:latest

      - name: Build Nginx Docker Image
        run: |
          docker build \
            --target nginx_server \
            --build-arg BUILD_ARGUMENT_ENV=prod \
            -t ${{ env.IMAGE_NGINX_BASE }}:${{ env.SHORT_SHA_ENV }} \
            -t ${{ env.IMAGE_NGINX_BASE }}:latest \
            -f .docker/common/Dockerfile .

      - name: Push Nginx Docker Image
        run: |
          docker push ${{ env.IMAGE_NGINX_BASE }}:${{ env.SHORT_SHA_ENV }}
          docker push ${{ env.IMAGE_NGINX_BASE }}:latest
